[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zubiya Ansari", email = "zubiyaansari417@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "requests>=2.34.2",
    "uvicorn>=0.52.4",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
